### ISSUE TITLE
Add documentation theme for each documentation engine

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/scicookie#108]
### Summary

Add documentation theme for each documentation engine, the options would be exclusive for each engine.

### Additional Information

```python (paste below)

```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by YurelyCamacho** [comment]
@xmnlab This means that after selecting the documentation engine, the user can select among several themes the one he/she prefers or have a default one for each documentation engine.
Currently mkdocs uses material theme and sphinx has html_theme = "sphinx_rtd_theme".

**Comment by xmnlab** [comment]
For those which it has just one option we can have just that as default .. otherwise we should show the options.

Doea it make sense?

**Comment by YurelyCamacho** [comment]
@xmnlab I understand that the one with more than one option is sphinx? md or rst. Is that what you mean?
I also believe that this will depend on the resolution of issue #28 which in turn depends on issue #171. 
Is that so?

**Comment by xmnlab** [comment]
not exactly related to #28, but for sure it depends on #171
we could have multiple themes for each doc engine ... for example the pydata sphinx theme
although we planned #171 for gsoc, but maybe I will need to move that forward to unblock the other tasks

**Comment by YurelyCamacho** [comment]
@xmnlab Perfect, right now this issue is assigned in the PSF grant to Anavelyz
