### ISSUE TITLE
.pre-commit-config.yaml doesn't reflect the option for src layout

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/scicookie#120]
### Summary

.pre-commit-config.yaml doesn't reflect the option for src layout

### Additional Information

```python (paste below)

```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Saransh-cpp** [comment]
I think this was handled in #125?

**Comment by xmnlab** [comment]
@Saransh-cpp your're totally right! thanks!
