### ISSUE TITLE
Add NumFOCUS CoC option

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/scicookie#142]
### Summary

Add NumFOCUS CoC as an option for CoC

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by YurelyCamacho** [comment]
@xmnlab There is a short version and a long version, which one is included?
https://numfocus.org/code-of-conduct

**Comment by xmnlab** [comment]
IIRC people can use the short version on webpages or in the README file,
but for the CoC file it should be the longer version

**Comment by YurelyCamacho** [comment]
Perfect, thanks.

**Comment by YurelyCamacho** [comment]
@xmnlab in the NumFOCUS Coc in section Conflicts of Interest this appears: 

If you are concerned about making a report that will be read by any of the above individuals, please reach out to [Leah Silen](mailto:leah@numfocus.org), Executive Director of NumFOCUS (https://numfocus.org/code-of-conduct#persons-responsible). [MAY WANT TO INSERT LANGUAGE HERE DESCRIBING THE RELATIONSHIP BETWEEN THE PROJECT AND NUMFOCUS. E.G. "[PROJECT] IS AN AFFILIATED PROJECT OF NUMFOCUS."]

what do I put in that case?

**Comment by xmnlab** [comment]
I didn't find it here: https://numfocus.org/code-of-conduct#persons-responsible

where are you getting that from?

**Comment by xmnlab** [comment]
got it.  so we need to be careful about what we will use here.

this code of conduct just make sense for affiliated projects with numfocus .. we cannot ask people to reach out numfocus if their project are not affiliated to them.

so anything specific for numfocus cannot be used.

but this CoC is under CC license, so we can adapt it and use it (but we need to cite the original file).

So, we cannot say that it is a NumFOCUS CoC, instead we can say `NumFOCUS-Adapted Code of Conduct`

does it make sense?

**Comment by YurelyCamacho** [comment]
Yes, I understand. Thanks.

**Comment by YurelyCamacho** [comment]
Ok, I will keep that in mind. Thanks @Anavelyz

**Comment by xmnlab** [comment]
done via #224
