### ISSUE TITLE
Add Python CoC  support

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/scicookie#143]
### Summary

Add Python CoC as an option for CoC

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by xmnlab** [comment]
@d1vyanshu-kumar this would is a very simple implementation but it touches a lot of parts
take a look if it is something that you would like to work on.

you will need to add the content for this CoC, change the cookiecutter.js, and the profiles as well, and of course, documentation. the main part of the magic happens here https://github.com/osl-incubator/scicookie/blob/main/src/scicookie/hooks/post_gen_project.py

**Comment by xmnlab** [comment]
@d1vyanshu-kumar ... sorry .. it seems this issue is already allocated to a project under a PSF Grant (Python Software Foundation)

I will add you to another issue similar .. so it would be easy to just update what you are already doing

**Comment by d1vyanshu-kumar** [comment]
@xmnlab Okay, no problem. I would be happy to solve it. Please assign me another issue.

**Comment by xmnlab** [comment]
done via #222
