### ISSUE TITLE
Remove noqa in profile.py

### ISSUE THREAD

**Issue by Anavelyz** [osl-incubator/scicookie#146]
### Summary

The `makim tests.lint` shows that there are two errors for ruff ( `RUF012 Mutable class attributes should be annotated with typing.ClassVar`), for that reason two `noqa` were added.

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by xmnlab** [comment]
I think this one is already done, otherwise feel free to re-open it please

**Comment by Anavelyz** [comment]
In profile.py there are still two noqa 🤔:
https://github.com/osl-incubator/scicookie/blob/9aed15b5cb3eba56e51b8af1934b7a9814ef4ea5/src/scicookie/profile.py#L20-L21

**Comment by xmnlab** [comment]
ow .. I missed that this was specific for ruff .. but I think it is ok to close this issue .. this something that we will not change for now ... basically we are not creating the classes in a "pythonic" way .. in some way we are mixing classvars and instance classes ... but I think that it would be ok for now .. we have the same issue for the other projects in incubation as well XD
