### ISSUE TITLE
Add py.typed when mypy is selected

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/scicookie#155]
### Summary

Some references:

* https://github.com/python-poetry/poetry/issues/1338
* https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker
* https://stackoverflow.com/a/57815124

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Saransh-cpp** [comment]
Related #157.

We won't have to delete py.typed if we keep `mypy` as a default tool (which it indirectly is right now).
