### ISSUE TITLE
Add API documentation to the template for sphinx-md (myst)

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/scicookie#173]

**Comment by Saransh-cpp** [comment]
@YurelyCamacho are you still working on this? If not, @Naman-Priyadarshi could you pick this up too?

**Comment by YurelyCamacho** [comment]
@Saransh-cpp I am not working on this now but with @EverVino  we assigned the PSF grant issues, so I would prefer to keep them assigned as they are. Thanks

**Comment by Saransh-cpp** [comment]
Oh I see, I missed that. Thanks for informing me! @Naman-Priyadarshi please avoid the psf grant issues (my bad).
