### ISSUE TITLE
template: move the mkdocs.yaml file to the root of the project in the post-gen script 

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/scicookie#177]
As pointed by @Anavelyz , the mkdocs.yaml should be located at the root of the file and the corresponding configuration should be updated: https://github.com/osl-incubator/scicookie/pull/112#discussion_r1225943014

**Comment by passingball** [comment]
Can I work on this issue? @xmnlab @Saransh-cpp @ayeankit

**Comment by Saransh-cpp** [comment]
Yes, please go ahead

**Comment by ayeankit** [comment]
Sure, You just have to create a funtion in post-gen script to move it root folder.

**Comment by d1vyanshu-kumar** [comment]
@Saransh-cpp I like this problem. can I try?

**Comment by Saransh-cpp** [comment]
A PR for this is open. I can assign you the issue next week if there is no response from the author.

**Comment by Anavelyz** [comment]
I'm working on it.

Thanks @passingball for trying!
