### ISSUE TITLE
Some requests as a user

### ISSUE THREAD

**Issue by EverVino** [osl-incubator/scicookie#184]
### Summary

I created a project with cookie cutter. I found that

- [x] Documentation [here ](https://osl-incubator.github.io/scicookie/intro.html) is not updated I'm assuming that is the official docs because is in the repo gh page
- [x] When I created the project the main branch has different name like `add-initial-structu..`  is not standard
- [x] I'd like to have an easy start, It will be great to have an yaml file to start with conda or a pyproject.toml to install an initial virtual env
- [x] I'd like to have an option use another docs generator. I want to use another static site generator like hugo for docs

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by xmnlab** [comment]
> Documentation [here ](https://osl-incubator.github.io/scicookie/intro.html)is not updated I'm assuming that is the official docs because is in the repo gh page

thanks for caching that!

> When I created the project the main branch has different name like add-initial-structu.. is not standard

yes, that is because it couldn't change the main directly for a bunch of reason ... and you should open a PR to main from there. if you don't have a main branch in your remote that branch would be defined as default, that is not good ... maybe we could check first if there is a main branch on remote, otherwise, it could create the branch as main

>  I'd like to have an easy start, It will be great to have an yaml file to start with conda or a pyproject.toml to install an initial virtual env

could you give more details about that?

>  I'd like to have an option use another docs generator. I want to use another static site generator like hugo for docs

I think that hugo is not in the plan for now, we have already options for sphinx, mkdocs and jupyter-book, and we are planning to add support for quarto. but if you want to contribute with hugo support, it would be very welcome :)

**Comment by EverVino** [comment]
> I'd like to have an easy start, It will be great to have an yaml file to start with conda or a pyproject.toml to install an initial virtual env
 
- To create a project I'd like to have a default option (an options that to avoid selecting ... ) 
- After creating the project, there were dependencies that were not installed (linters, mkdocs...), these dependencies could be named somewhere, or depending on whether poetry or conda was chosen, a file could be created from which the dependencies were installed additional ones from a pyptoject or yaml.
Maybe it could be included in the starting-up
- Requirements: python
- Install via pip scicookie
- Enable the virtual environment (via poetry, conda... pdm; requirements...)
These steps may be very obvious to many developers, it may be good to wait for feedback.

In the first push to the remote repository the CI failed, I have no idea why, I will check, but that time I will only add a file with comments in the code.
 
> I think that hugo is not in the plan for now, we have already options for sphinx, mkdocs and jupyter-book, and we are planning to add support for quarto. but if you want to contribute with hugo support, it would be very welcome :)

Ok, I'm starting to think how to add hugo.

**Comment by xmnlab** [comment]
about the error, if the repo you are trying to use is mass-transfer-py
https://github.com/osl-pocs/mass-transfer-py/actions/runs/6240174858/job/16939678221#step:3:172

it seems that it doesn't have the conda/dev.yaml and this is trying to use it

I don't remember if you have conda as an option now ...

**Comment by xmnlab** [comment]
@EverVino , I think we can already close this issue.
feel free to open a new one if you find more things to be fixed or be implemented.
thanks
