### ISSUE TITLE
ERROR: The project slug (anamnesis.ai) is not a valid Python module name.

### ISSUE THREAD

**Issue by Satarupa22-SD** [osl-incubator/scicookie#197]
Error encountered while creating an initial structure for the project using scicookie.
ERROR: The project slug (anamnesis.ai) is not a valid Python module name.Please do not use a - and use _ instead.

<img width="1440" alt="Screenshot 2024-01-05 at 7 05 48 PM" src="https://github.com/osl-incubator/anamnesis.ai/assets/84276219/dd34ff39-6a0a-4ca5-a215-b16911869880">

**Comment by xmnlab** [comment]
cc @abhijeetSaroha

**Comment by xmnlab** [comment]
if you need to use regex, maybe you could use jinja2 `set` command, example: `{% set name = "ai".upper() %}`

**Comment by abhijeetSaroha** [comment]
@xmnlab 
`pre_gen_project.py`, in this file, It is checking the package_slug and in error it is printing the project_slug. So, I am little confused in which extra symbols are allowed and in which not or in both, the extra symbols are not allowed.

Can you please check it?

![image](https://github.com/osl-incubator/scicookie/assets/108522472/467f4edd-f8f5-4197-90e0-7db1ff1c324c)

**Comment by xmnlab** [comment]
I think it is ok there .. we shouldn't add any extra character there

**Comment by xmnlab** [comment]
done via #245
