### ISSUE TITLE
ideas for the logo

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/scicookie#199]
![DALL·E 2024-02-01 14 21 36 - Design a stylized cookie with an atom symbol in the center, symbolizing a blend of baking and science, particularly focusing on scientific Python proj](https://github.com/osl-incubator/scicookie/assets/5209757/cf8d2ae6-e85e-4ec6-8420-a03f17367ea7)

![DALL·E 2024-02-01 13 29 33 - Design a stylized cookie with an atom symbol in the center, symbolizing a blend of baking and science, particularly focusing on scientific Python proj](https://github.com/osl-incubator/scicookie/assets/5209757/9a947724-4e95-4525-9350-136ec813acd5)

thumbnail for youtube:

![scicookie-thumbnail](https://github.com/osl-incubator/scicookie/assets/5209757/327dacdd-aeb6-4a13-b76e-70ccad1f8e19)

**Comment by Naman-Priyadarshi** [comment]
Hi @xmnlab, You recently added the logo to the documentation, and I wanted to inform you that the logo is not visible in the dark mode version of the webpage.

**Comment by xmnlab** [comment]
Hey @Naman-Priyadarshi , appreciate your feedback about the logo. I am aware of that. I just wanted to replace the default logo.I don't really have time right now to work on that. But thanks for reporting that. It would be nice if someone could work on that

**Comment by xmnlab** [comment]
Also maybe we would like to change the logo as well, it was just a temporary logo for now

**Comment by xmnlab** [comment]
I think we are good for now, maybe in the future we can revisit this.
