### ISSUE TITLE
Incorrect Setup Instructions in CONTRIBUTING for Local Development

### ISSUE THREAD

**Issue by Naman-Priyadarshi** [osl-incubator/scicookie#203]
### Overview
The current setup instructions provided in the CONTRIBUTING.md for local development are outdated and incorrect. The instructions suggest using `python setup.py develop` for installation, but the `setup.py` file does not exist in the repository. This issue could also help in fixing the CONTRIBUTING.md in the template too

### Proposed Solution:
Update the CONTRIBUTING file with accurate and up-to-date instructions for local development. This may involve recommending alternative methods for installation, such as using Poetry `poetry install` or pip `pip install -e .`.

### Documentation Page Link

https://osl-incubator.github.io/scicookie/contributing.html#get-started

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by Saransh-cpp** [comment]
Yes, the documentation is really out of date. Thanks for pointing this out!
