### ISSUE TITLE
Update Pull Request Template to Ensure Proper Linking with Issues

### ISSUE THREAD

**Issue by Naman-Priyadarshi** [osl-incubator/scicookie#217]
~* Date you used Cookiecutter Python Package:~
~* Cookieninja version used, if any:~
~* Python version, if any:~
~* Operating System:~

### Description

The Pull request template for both scicookie and the template uses `solves #xyz` instead of `fixes #xyz` which doesn't link the pull request to the issue. A very small change could help in making the process much smoother

**Comment by agriyakhetarpal** [comment]
I think https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword does list `solves`, doesn't it?
