### ISSUE TITLE
Missing Project Description on PyPI

### ISSUE THREAD

**Issue by Naman-Priyadarshi** [osl-incubator/scicookie#240]
### Summary

I was checking out scicookie on PyPI and found out that there is currently no project description available.

### Documentation Page Link

https://pypi.org/project/scicookie/

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by xmnlab** [comment]
@Satarupa22-SD 
Please take a look into this issue.
It should be something really simple.

**Comment by Satarupa22-SD** [comment]
@xmnlab sure :)
