### ISSUE TITLE
Rye, a comprehensive project and package management solution for Python

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/scicookie#258]
maybe something to keep on our radar: https://github.com/astral-sh/rye

**Comment by YurelyCamacho** [comment]
@xmnlab Can I close this topic? I am now working on the proposal for SciCookie and am debugging the list. Thanks

**Comment by xmnlab** [comment]
it seems that the rye was a bit challenging to implement. 
also we would need to have the package available on conda forge as well.
