### ISSUE TITLE
add gitlab ci to the template

### ISSUE THREAD

**Issue by EverVino** [osl-incubator/scicookie#264]
### Summary

To let to the user have the option to select gitlab CI instead of the github CI
https://docs.gitlab.com/ee/ci/

### Additional Information

```python (paste below)

```

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by YurelyCamacho** [comment]
@xmnlab @EverVino Could you give me a guide of the steps to follow. I have been reading the reference left and looking at other Gitlab CI/CD template links. Thanks

**Comment by EverVino** [comment]
A first approach could be, create your own remote gitlab repo and check what are the differences.
The main issue is replace github with gitlab (remote repo in git config)
github has in .github/workflows/main.yaml, gitlab should have something similar to that

**Comment by xmnlab** [comment]
@YurelyCamacho as reference .. you can try to get the output for the github CI from the current template, and ask gpt to convert it to gitlab ci ... then you can try that on gitlab to check if that works fine

**Comment by xmnlab** [comment]
ref https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.gitlab-ci.yml

**Comment by YurelyCamacho** [comment]
@xmnlab @EverVino One question, currently scicookie has a .github/workflows/main.yaml and another .github/workflows/release.yaml. The equivalence for gitlab CI should be a single .gitlab-ci.yml file.

**Comment by xmnlab** [comment]
I am not sure how gitlab works .. if we could have multiple workflow files that would be great... otherwise we would need to keep both in the same file ...

**Comment by YurelyCamacho** [comment]
I asked the question to an LLM and he tells me that a single .gitlab-ci.yaml file

**Comment by xmnlab** [comment]
completed, thanks @YurelyCamacho
