### ISSUE TITLE
Split documentation engine sphinx into  sphinx-md and sphinx-rst

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/scicookie#28]
ideally if sphinx is selected, it should show an option for source format md or rst

**Comment by xmnlab** [comment]
depends on #171

**Comment by YurelyCamacho** [comment]
@xmnlab What do you think the process should be like here? Leave the sphinx option and if it is selected then either md or rst should be displayed, or both options should be displayed and only one of them should be allowed to be used?
I know this depends on issue #171 but it is to think about how it should be done.

**Comment by xmnlab** [comment]
We can implement it in 2 phases.

- 1st (i don't remember if it is already implemented) without "depends-on" option, we could have sphinx-rst and sphinx-md
- 2nd phase, with "depends on", we could have just sphinx, and if it is selected, it could show an question called sphinx-format with options markdown and rst

Does it make sense?

**Comment by YurelyCamacho** [comment]
@xmnlab I think what you are talking about refers to issue 171. A few months ago you marked that this issue depends on that one. So I will wait for it to be resolved. Thanks
