### ISSUE TITLE
bug: .github folder is missing in osl profile

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/scicookie#319]

**Comment by Anavelyz** [comment]
@xmnlab Is it because this should be `visible: true`?
https://github.com/osl-incubator/scicookie/blob/d9497ac550d8ef4e2f2f7d0be29813839786245e/src/scicookie/profiles/osl.yaml#L108C1-L111C17

**Comment by xmnlab** [comment]
we should keep it as "no" in the cookiecutter.json 

and it shouldn't be visible 

I am not sure .. maybe we just need to add a default value, for example, https://github.com/osl-incubator/scicookie/blob/main/src/scicookie/profiles/osl.yaml#L55

and set it to github_actions

**Comment by Anavelyz** [comment]
> we should keep it as "no" in the cookiecutter.json
> 
> and it shouldn't be visible
> 
> I am not sure .. maybe we just need to add a default value, for example, https://github.com/osl-incubator/scicookie/blob/main/src/scicookie/profiles/osl.yaml#L55
> 
> and set it to github_actions

Currently, the options that have a default value are single-choice, in this case it is multiple-choices, this depends on the default value in the cookiecutter.json. Should anything else be configured?
