### ISSUE TITLE
Migrate from `flake8` and `isort` to `ruff`

### ISSUE THREAD

**Issue by Saransh-cpp** [osl-incubator/scicookie#65]
### Description

[`ruff`](https://github.com/charliermarsh/ruff) is extremely fast and is now being adopted widely by scientific packages. With the migration, we will be able to get rid of `isort` and `flake8-pyproject` from `pre-commit-config.yaml`.

Additionally, ruff can also automatically fix the captured errors, which can be an advantage when using `pre-commit.ci` (see https://github.com/osl-incubator/cookiecutter-python/pull/62#issuecomment-1472528783).

**Comment by Saransh-cpp** [comment]
The changes should be made to both, the [base `pre-commit-config.yaml`](https://github.com/osl-incubator/cookiecutter-python/blob/main/.pre-commit-config.yaml) file and the [template `pre-commit-config.yaml`](https://github.com/osl-incubator/cookiecutter-python/blob/main/%7B%7Bcookiecutter.project_slug%7D%7D/.pre-commit-config.yaml) file.

**Comment by xmnlab** [comment]
@Saransh-cpp that is a great idea. also it is something I had in mind for a while.

I agree to move to move the project (base) to ruff !

about the template, I think it should be an option, and we can have it as default, because maybe some people would want to keep the known workflow with flake8

**Comment by Saransh-cpp** [comment]
I hadn't considered about providing users with an option for the formatting libraries. That sounds great!

**Comment by ayeankit** [comment]
Hey @xmnlab This issue also covered in PR #130. Can you please check this again?

**Comment by xmnlab** [comment]
You're right! Thanks @ayeankit
