### ISSUE TITLE
Better issue templates

### ISSUE THREAD

**Issue by Saransh-cpp** [osl-incubator/scicookie#66]
### Description

Currently, cookiecutter-python only has a bug report template, which is also the default template. The templates can be updated to include feature requests, documentation issues, and so on. Additionally, we can switch to form-based issues (YAML-based issue templates) for more user-friendliness.

For reference, I really like pyhf's issue templates - https://github.com/scikit-hep/pyhf/tree/main/.github/ISSUE_TEMPLATE

**Comment by ayeankit** [comment]
Hey @Saransh-cpp, I am interested in implementing these templates for feature requests, documentation issues, and so on. Please assign me this.

**Comment by Saransh-cpp** [comment]
Sure, go ahead!

**Comment by xmnlab** [comment]
thank you both @Saransh-cpp and @ayeankit !
