### ISSUE TITLE
Rename the project to osl-python-template

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/scicookie#88]
We moved the project from cookiecutter to cookieninja, and probably we should have a name more flexible about the backend used.

so my suggestion is to rename it to  osl-python-template

Also, it would fit well if we decided to also add an option for a CLI program, so, additionally to the current call (`cookieninja https://github.com/osl-incubator/cookiecutter-python`), we would have an option to call it via CLI, for example `osl-python-template`.

**Comment by xmnlab** [comment]
TBH probably we would need a better and shorter name to the project. 
but for now it is ok that.
also because if we implement some kind of profile so any communities could have a way to specify their subset of choices and options .. so it would be better to have a project with a neutral name as well.

**Comment by Anavelyz** [comment]
@xmnlab This is done, right?

**Comment by xmnlab** [comment]
@Anavelyz , you're right. thanks
