### ISSUE TITLE
Add makim as an option for automation tool 

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/scicookie#91]
currently, the template offers `make` automatically without asking.
it would be nice to have an option for automation_tools. where it will allow makim (default) or make

**Comment by ayeankit** [comment]
Hi @xmnlab , Can you explain more about the workflow of automation_tool used in the template?

**Comment by xmnlab** [comment]
we could have support for some automation tools  like makim, make, ansible etc
makim and make could be used to automatize some tasks in the project, in order to facilitate our lives, so we don't need to remember all the commands and their parameters

ansible is similar, but it is more powerful because it has a bunch of integrations and is very used for deployment
