### ISSUE TITLE
create a CLI for osl-python-template (cookiecutter-python)

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/scicookie#97]
in order to facilitate the call and installation of dependencies for this template, it would be nice to have a CLI that will call cookieninja.

What would be nice to have:

- parsing the CLI arguments using argparse
- in order to define all the argparse, we could use the information from cookiecutter.json
- instead of using for the prompt the name of the variable, it would be nice to use a description, we need to think on some nice way to extend the current cookiecutter.json in order to add more useful information

This is an idea about how it would look like (I will update it every time we have a better idea)

```bash
$ osl-python-template
You've downloaded /home/xmn/.cookiecutters/cookiecutter-python before. Is it okay to delete and re-download it? [yes]: 
Author's name [Roronoa Zoro]: 

Author's email [zoro@one.piece]: 

Project name, the title of the project [OSL Python package]:

Project short description [OSL Python Package contains all the boilerplate you need to create a Python package.]: 

Project Slug, the code name for your project, e.g. the name used for the code repository [pyopensci-template]: 

Package slug, the code name for your package, e.g. the name used to import your package [pyopensci_template]: 

Project version [0.1.0]: 

Project url [https://pyopensci-template.com]:          

Select the project license:
Note: see https://url.com/endpoint
> MIT
  BSD 3 Clause
  ISC license
  Apache Software License 2.0
  GNU General Public License v3
  Other

# if Other is selected
License name:
License URL:

Select the project layout:
Note: see https://url.com/endpoint
> src layout
  flat layout

Select the Command Line Interface (CLI):
Note: see https://url.com/endpoint
> Click
  Argparse
  docopt
  Typer
  No CLI

Select the Documentation Engine:
Note: see https://url.com/endpoint
> MkDocs
  Sphinx
  Quarto

Select the template for the Documentation Engine
Note: see https://url.com/endpoint
> Material

Select the test library:
Note: see https://url.com/endpoint
> pytest
  hyphotesis
  unittest

Select Code of Conduct:
Note: see https://url.com/endpoint
> Contributor Covenant (projects of all sizes)
  Citizen Code of Conduct (communities and events)
  None

Select a governance document template from:
> NumPy governance document
  SciML governance document
  None

Select a Roadmap document template from:
Note: see https://url.com/endpoint

> PyTorch-Ignite roadmap document
  None


Select the initial tools you want to add to your project :
Note: see https://url.com/endpoint
   [X] blue
   [X] black
   [X] shellcheck
   [ ] bandit 
   [ ] pydocstyle
   [ ] vulture
   [ ] mccabe

Select the container technology for this project:
Note: see https://url.com/endpoint
> None
  Docker
  Podman
  kubernetes

Configure the local git repository? [yes]:
Note: see https://url.com/endpoint

# if answer is yes
git username [zoro_roronoa]: 

git https origin URL []: 

git https upstream URL []: 

git main branch [main]: 

Configure the pypi username? [yes]: 

# if answer is yes
pypy username [zoro_roronoa]:
```

**Comment by xmnlab** [comment]
@ayeankit could you prioritize this issue?
it seems it would be necessary earlier than latter

**Comment by ayeankit** [comment]
@xmnlab Sure, start working on that.

**Comment by xmnlab** [comment]
Nice! Thanks! I will provide more details about this today.
But for now you can study about argparse and json lib.
I will try to provide some snippet too

**Comment by xmnlab** [comment]
reviewing a bit some CLIs options, it seems that click would be a better fit for this challenge
https://towardsdatascience.com/how-to-write-user-friendly-command-line-interfaces-in-python-cc3a6444af8e

**Comment by xmnlab** [comment]
if we decide to use `courses` for the link, I am sharing here a snippet about how to use it:

```
import curses

def create_link_text(text, url):
    return f"{text} ({url})"

def main(stdscr):
    # Clear the screen
    stdscr.clear()

    # Create the link text
    link_text = create_link_text("Click here", "https://www.example.com")

    # Display the link text
    stdscr.addstr(0, 0, link_text, curses.A_UNDERLINE | curses.A_STANDOUT)

    # Refresh the screen
    stdscr.refresh()

    # Wait for user input
    stdscr.getch()

# Initialize the curses module
curses.wrapper(main)
```

**Comment by xmnlab** [comment]
but I guess that probably we would prefer to use something simpler than `courses`.

it is not perfect, but maybe if we have just a tiny url for each documentation page, it would works good enough and
we give the responsibility to create a clickable link to the terminal.

this is an example using a library called colorama (just for the colors):

```python

from colorama import init, Fore, Style

def create_link_text(text, url):
    return f"{Fore.BLUE}{Style.BRIGHT}{text}{Style.RESET_ALL} ({Fore.GREEN}{Style.BRIGHT}{url}{Style.RESET_ALL})"

# Initialize colorama
init()

# Example usage
link_text = create_link_text("Click here", "https://www.example.com")
print(link_text)
```

**Comment by xmnlab** [comment]
@ayeankit could you please study click and colorama?

**Comment by xmnlab** [comment]
for options, instead of the usual why provided by cookiecutter, we could try inquirer.

here there is a snippet how to use it:

```
import inquirer
questions = [
  inquirer.Checkbox('interests',
                    message="What are you interested in?",
                    choices=['Computers', 'Books', 'Science', 'Nature', 'Fantasy', 'History'],
                    ),
]
answers = inquirer.prompt(questions)
~                                      
```

**Comment by xmnlab** [comment]
@lwasser, we will be discussing here some topics we discussed from our meeting yesterday.
so the CLI would be the main interface with the end-user
feel free to add any idea you would like to have in the CLI please

**Comment by ayeankit** [comment]
@xmnlab I have some experience in argparse, can we do it using argparse?

**Comment by xmnlab** [comment]
@ayeankit in this case, probably `inquirer` would be the way to go ... the experience is much better.

what we need:

1. a good experience for interactive choices and multiple choices
2. nested options

argparse doesn't have any of these two requirements 
and click doesn't have a good experience for interactive choices and multiple choices

probably we should offer both interactive and non-interactive .. for non-interactive .. we can just pass the same arguments received to cookieninja .. and it could be done as a follow-up

but for the interactive approach probably we should go with inquirer

does it make sense?

**Comment by ayeankit** [comment]
@xmnlab Sure going for `inquirer` but I didn't think of these points. `inquirer` will be an excellent option for both interactive and non-interactive.
